import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { Providers } from "./providers";
import { Footer } from "@/components/ui/footer";

const poppins = Poppins({
  weight: ["200", "300", "500", "600", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FSW store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/assets/favicon.png" sizes="any" />
      </head>
      <body className={poppins.className}>
        <Providers>
          <Header />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
